[tool.poetry]
name = "pytest_playground"
version = "0.1.0"
description = "Experiment with global pytest fixtures"
authors = ["Clement Goh <shipitparrot@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.2"
ruff = "^0.0.292"
black = "^23.9.1"
mypy = "^1.5.1"